### ISSUE TITLE
Static file links

### ISSUE THREAD

**Issue by grapheo12** [metakgp/metakgp-wiki#101]
The Nginx Dockerfile doesn't copy the peqp dump to /srv/static by default. This has to done by hand.
Recently the server had to be restarted which led to the deletion of the static files.
Maybe we should add some code so that this addition automatically happens with new builds.

@icyflame @amrav @thealphadollar

**Comment by icyflame** [comment]
IIRC, the static files are mounted into `/srv/static` through a volume. So, even if the server is restarted or the containers are stopped and started again etc, the files will remain on the host in that volume and will be mounted into that folder the next time the containers are started using `docker-compose up`

For this particular issue, can you add more detail about what you did, what actually happened, what you expected to happen and your proposal to fix that (optional).

**Comment by harshkhandeparkar** [comment]
Closing this due to lack of information
