### ISSUE TITLE
Add commands used to restart all containers to the RUNBOOK

### ISSUE THREAD

**Issue by icyflame** [metakgp/metakgp-wiki#52]
I had to restart all the containers on our server because the memory usage was as high as 85% and this triggered a Newrelic alert for `Error rate > 10%`.

One of the errors I saw on the website was `unable to fork() - cannot allocate memory`

[Slack thread][1]

[1]: https://metakgp.slack.com/archives/C0AHQDVEH/p1559519080001400

**Comment by thealphadollar** [comment]
@icyflame I believe this can be closed.

**Comment by icyflame** [comment]
@thealphadollar I agree! This recipe can be used to restart everything: https://github.com/metakgp/metakgp-wiki/blob/master/RUNBOOK.md#i-just-want-everything-to-start-and-run-like-a-normal-server
