### ISSUE TITLE
$wgStyleVersion`is now removed from mediawiki but extension:Maps still uses it

### ISSUE THREAD

**Issue by icyflame** [metakgp/metakgp-wiki#55]
[`$wgStyleVersion`][1] was removed completely since Mediawiki 1.32. This is used inside the Maps extension [here][2]. We use Maps v4.4.0. 

We don't seem to be having any problems with our current setup, but if something does come up related to the Maps extension, we might have to update the version of the extension we use.

[1]: https://www.mediawiki.org/wiki/Manual:$wgStyleVersion
[2]: https://github.com/JeroenDeDauw/Maps/blob/4.4.0/Maps.php#L98

**Comment by amrav** [comment]
Maps upgraded in #60, closing.
