### ISSUE TITLE
Add peqp to monthly backups

### ISSUE THREAD

**Issue by amrav** [metakgp/metakgp-wiki#6]

**Comment by icyflame** [comment]
@amrav The `peqp/` folder resides inside `/srv/mediawiki` in the nginx container. So, we need to put that file into the archive that is prepared [here](https://github.com/metakgp/metakgp-wiki/blob/master/backup/run_backup.sh#L31). If my understanding is correct, I can go ahead and try to solve this.

**Comment by amrav** [comment]
I've been thinking that the best way to add static assets (images, peqp) to the wiki server is to put them into a separate "static assets" volume, and serve them out of a different path (eg. `/srv/static`). This has the advantage of making the `mediawiki` volume completely ephemeral - right now, we lose images and peqp every time we redeploy. Then the backup container could do backups from the static assets volume.

This would require some changes to the nginx container though, to add configuration for serving the static assets. What do you think?

**Comment by icyflame** [comment]
I understand this a bit more now. I will read through the existing code and documentation and try to figure out how we would do this. For now, I think there should be a volume called "static" which will be accesible at /srv/static inside the nginx container (defined in the docker-compose.override.yml file)

This is only preliminary and probably incorrect, I will post something for you to review soon.

**Comment by icyflame** [comment]
#27 puts peqp in the static volume, this issue has become a lot easier. I am changing the tags to let newcomers know that this is a good issue to begin with.

It involves changing [the backup script](https://github.com/metakgp/metakgp-wiki/blob/master/backup/run_backup.sh) to include the `/srv/static/peqp` folder (if it exists) inside the backup archive.

Also, the `prod` configuration needs to be edited to allow the `static-volume` to be mounted at `/srv/static` inside the backup container as well. 

(cc @amrav and @hargup)

**Comment by harshkhandeparkar** [comment]
Closing this since peqp will no longer be part of the wiki.
