### ISSUE TITLE
Replace the extension RecentChanges with SimpleChanges

### ISSUE THREAD

**Issue by icyflame** [metakgp/metakgp-wiki#79]
The extension we are using, [RecentChanges][1] doesn't seem to be supported any longer.

[![image](https://user-images.githubusercontent.com/3668034/75638339-c638f180-5c6e-11ea-8bff-4ad21750d6b0.png)][1]

[1]: https://www.mediawiki.org/wiki/Extension:RecentPages

Whereas the [SimpleChanges][1] extension looks promising:

> The SimpleChanges extension creates a Special page that displays a barebones Recent Changes list. It is ideal for transclusion.
-- [SimpleChanges][1]

[1]: https://www.mediawiki.org/wiki/Extension:SimpleChanges

**Comment by harshkhandeparkar** [comment]
This extension was never used lol.
